name: bebebe_blog
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/

  fonts:
    - family: Aihara
      fonts:
      - asset: assets/fonts/AiharaSignPen_free.ttf

    - family: Hui
      fonts:
      - asset: assets/fonts/HuiFont.ttf

    - family: Kawaii
      fonts:
      - asset: assets/fonts/KTEGAKI.ttf

    - family: Otsutome
      fonts:
      - asset: assets/fonts/OtsutomeFont_Ver3_15.ttf